name: client

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12']
    name: Testing fensandemajiang's client with node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies and script
        run: yarn

      - name: Run TypeScript compiler
        run: yarn run tsc

      - name: Check linting with eslint
        run: yarn run lint:check

      - name: Check formatting with prettier
        run: yarn run format:check

      - name: Unit Test
        run: yarn run test:ci

      - name: Integration Test
        run: yarn run test:integration:ci
